### ISSUE TITLE
Publish dataset with Zenodo

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/tangclassifiers#9]
I'd say, now that all is in place, we could make sure to do the final step: publishing with Zenodo. 

@marctang, have a look at [.zenodo.json](https://github.com/cldf-datasets/tangclassifiers/blob/master/.zenodo.json). This file manages how the data will be represented in form of metadata on zenodo, so that it can be quoted, etc. This is important, as it may otherwise be misleading, etc., or the wrong people being quoted. 

So please check it and close this issue, once it is fine with you.

**Comment by marctang** [comment]
Sure! with the help of @xrotwang I could also import this CLDF dataset in the CLLD software! Awesome! Thanks for your help too :-D!

Just a final question: to release it on Zenodo, I just download the content from this repository and upload it in Zenodo, right?

**Comment by xrotwang** [comment]
@marctang releasing to Zenodo is actually simpler, since there's a [GitHub-Zenodo bridge](https://guides.github.com/activities/citable-code/). To use this, you'd have to log into Zenodo using your GitHub account, and then "switch on" this repos on your repository list at https://zenodo.org/account/settings/github/
If this is done, you should see the Zenodo webhook listed at https://github.com/cldf-datasets/tangclassifiers/settings/hooks

Alternatively - if you are willing to give up some control - we could do this. We have an institutional GitHub/Zenodo account which can be accessed by more people in our department to make sure we don't end up with orphaned datasets on Zenodo. (Only the submitter of a deposit on Zenodo can edit the metadata there.)

**Comment by LinguList** [comment]
and thanks to the .zenodo.json file, metadata can mostly handled before
actually submitting to zenodo.

**Comment by xrotwang** [comment]
@marctang looks good!

**Comment by marctang** [comment]
Thanks to you guys and the suggestions! I thought to try it myself just to be sure that I know how to update it later on and can teach others to do it if needed. I was trying it before I reply and it went much faster than I thought!  Super thanks to you guys and the community! :-D

**Comment by xrotwang** [comment]
@marctang I typically add the link to the Zenodo record on the release page (see https://github.com/cldf-datasets/tangclassifiers/releases/tag/v1) to make it clear what the authoritative (and longterm) location of the released data is.

**Comment by marctang** [comment]
@xrotwang  Thanks for the suggestion! I just added the link to the Zenodo record on the release page!
